version: "2"

linters:
  default: standard

  exclusions:
    rules:
      - linters:
          - staticcheck
        text: QF1001

  # enable:
  #   - bodyclose
  #   - copyloopvar
  #   - depguard
  #   - dogsled
  #   - dupl
  #   - errcheck
  #   - errorlint
  #   - funlen
  #   - gocheckcompilerdirectives
  #   - gochecknoinits
  #   - goconst
  #   - gocritic
  #   - gocyclo
  #   - godox
  #   - mnd
  #   - goprintffuncname
  #   - gosec
  #   - govet
  #   - intrange
  #   - ineffassign
  #   - lll
  #   - misspell
  #   - nakedret
  #   - noctx
  #   - nolintlint
  #   - revive
  #   - staticcheck
  #   - testifylint
  #   - unconvert
  #   - unparam
  #   - unused
  #   - whitespace
