#!/usr/bin/env slipr

;;;; Copyright (c) 2026, Peter Ohler, All rights reserved.

(defun display-help (&optional err)
  (typecase err
    (error (format t "~%>>> ~A <<<~%" (send err :message)))
    (string (format t "~%>>> ~A <<<~%" err))
    (t nil))
  (format t "~%~A

Explore the coverage of lisp code. The first argument must be a path to a
coverage file generated by slip. If no other filepaths are provided a list of
the filepaths in the coverage file are listed. If additional filepaths are
provided then the file is displayed with colors indicating whether a function
was called. A coverage percentage is display at the end of the file.

usage: ~A <coverage-file> [<filepath>...]
" (cadr *app-args*) (cadr *app-args*))
  (format t "  -i --include <regex>  include file (default: all files) ~%")
  (format t "  -x --exclude <regex>  exclude file (default: no exclusions) ~%")
  (format t "  -h --help             display help~%")
  (terpri))

(defun calculate-coverage (cov-fun filepath)
  "Calculates the coverage percentage for a file if filepath is a string. If
   filepath is nil then the overall coverage is calculated. If filepath is a
   list of files then only files in the list are used for the summary."
  (let ((covered 0)
        (total 0))

    (dolist (fn cov-fun)
      (when (or (null filepath)
                (and (stringp filepath) (suffixp (car fn) filepath))
                (and (listp filepath) (member (car fn) filepath)))
        (incf total)
        (unless (= 0 (nth 5 fn)) (incf covered))))

    (cond ((= total 0) 0)
          (t (/ (* covered 100) total)))))

(defun filter-filepath (filepath includes excludes)
  "File a pathname with the includes and excludes where both the includes and
   excludes are lists of regexp strings. A filepath passes if it is in the
   includes and not in the excludes. An empty or nil includes passes any
   filepath unless it matches a regexp in the excludes."
  (let ((pass (emptyp includes)))
    (dolist (rx includes)
      (when (regex-match rx filepath) (setq pass t)))
    (dolist (rx excludes)
      (when (regex-match rx filepath) (setq pass nil)))
    pass))

(defun display-file-list (cover includes excludes)
  "Display a list of the files in the coverage information along with the
   coverage of each and the overall coverage."
  (let ((cov-files (car cover))
        filepaths)
    (loop
     (when (emptyp cov-files) (return 'done))
     (when (filter-filepath (car cov-files) includes excludes)
       (addf filepaths (car cov-files)))
     (setq cov-files (cddr cov-files)))

    (sort filepaths)

    (dolist (filepath filepaths)
      (format t "~A: ~,1F%~%" filepath (calculate-coverage (cdr cover) filepath)))

    (format t "Total coverage: ~,1F%~%" (calculate-coverage (cdr cover) filepaths))))

(defun locate-segment (line c0 c1)
  (let ((index 0))
    (dolist (seg line)
      (when (and (<= (car seg) c0)
                 (or (= (cadr seg) -1)
                     (< c1 (cadr seg))))
        (return index))
      (incf index))
    index))

(defun insert-segment (line c0 c1 cov)
  "Insert a new segment with c0 being the first column and c1 being the last."
  (let* ((index (locate-segment line c0 c1))
         (seg (nth index line))
         (seg0 (car seg))
         xline)
    (when (< seg0 0) (setq seg0 0))
    (when (< 0 index)
      (setq xline (subseq line 0 index)))
    (when (< seg0 c0) (addf xline (list seg0 c0 (caddr seg))))
    (addf xline (list c0 c1 cov))
    (when (< c0 c1) (addf xline (list c1 (cadr seg) (caddr seg))))
    (when (< (1+ index) (length line)) (subseq line (1+ index)))
    xline))

(defun form-segments (provs count)
  "Segments describe a segment of a line associated with a function. Each segment
   has a start, end, and coverage indicator of nil for no provenance,
   :covered, and :not-covered. An end of -1 indicates unbounded. Segments are
   organized by line to match the lines in a file."

  (let (lines)
    ;; Initialize lines with the no provenance indication of nil.
    (dotimes (n count)
      (addf lines (list (list -1 -1 nil))))

    (dolist (fn provs)
      (let* ((firstLine (cadr fn)) ;; lines are zero based
             (line (nth firstLine lines))
             (cov (if (< 0 (nth 5 fn)) :covered :not-covered))
             (lastLine (cadddr fn))
             (c0 (1- (caddr fn))) ;; columns are 1 based
             (c1 (nth 4 fn))) ;; one past last character

        (cond ((= firstLine lastLine) ;; same line
               (setf (nth firstLine lines) (insert-segment line c0 c1 cov)))
              (t
               (setf (nth firstLine lines) (insert-segment line c0 -1 cov))
               ;; Any lines inbetween first and last are set to one segment.
               (dotimes (n (- lastLine firstLine 1))
                 (setf (nth (+ firstLine n) lines) (list (list 0 -1 cov))))
               (setf (nth lastLine lines) (insert-segment (nth lastLine lines) 0 c1 cov))))
        ))
    ;; Compact lines. Remove (-1 0 nil) any with a end of zero at start if
    ;; present. Then merge consecutive segments with the same coverage.
    (dotimes (n count)
      (let ((line (nth n lines))
            comp ;; new compacted segment
            compact)
        (dolist (seg line)
          (cond ((= 0 (cadr seg)) nil) ;; skip segments ending at zero
                ((null comp) (setq comp seg))
                ((equal (caddr comp) (caddr seg)) ;; merge
                 (setf (cadr comp) (cadr seg)))
                (t ;; different coverage
                 (addf compact comp)
                 (setq comp seg))))
        (addf compact comp)
        (when (= 1 (length compact))
          (let ((seg (car compact)))
            (when (and (< 0 n) (= -1 (car seg)) (= -1 (cadr seg)) (null (caddr seg)))
              (setf (caddr seg) (caddar (last (nth (1- n) lines)))))))
        (setf (nth n lines) compact)))

    lines))

(defun colorize-lines (lines provs)
  (let ((segments (form-segments provs (length lines))))
    ;; Use the segments to reform each line with colors.
    (dotimes (n (length lines))
      (let ((line (nth n lines))
            (sline (nth n segments))
            (current-color *ansi-gray*)
            (colorized ""))
        (dolist (seg (nth n segments))
          (setq current-color (case (caddr seg)
                                (:covered *ansi-green*)
                                (:not-covered *ansi-red*)
                                (t *ansi-gray*)))
          (setq colorized (string-append colorized current-color))
          (cond ((= -1 (cadr seg))
                 ;; when still more left, append rest
                 (cond ((< (car seg) 0)
                        (setq colorized (string-append colorized line)))
                       ((< (car seg) (length line))
                        (setq colorized (string-append colorized (subseq line (car seg)))))))
                (t
                 (let ((last (cadr seg)))
                   (cond ((< (length line) last)
                          (setq colorized (string-append colorized (subseq line (car seg)))))
                         (t
                          (setq colorized (string-append colorized (subseq line (car seg) last)))))))))
        (let ((last (cadar (last (nth n segments)))))
          (when (and (<= 0 last) (< last (length line)))
            (setq colorized (string-append colorized
                                           (if (< (1+ last) (length line)) (subseq line last (1+ last)) "")
                                           current-color
                                           (subseq line (1+ last))))))
        (setf (nth n lines) colorized))))
  lines)

(defun display-cover-file (cover filepath destination)
  "Output a file colorized according to the coverage of each function."
  (let ((cov-fun (cdr cover))
        lines
        provs)
    ;; The filepath may be a partial path so find the first match and use that
    ;; as the target filepath.
    (setq filepath
          (dolist (fn cov-fun)
            (when (suffixp (car fn) filepath)
              (return (car fn)))))

    (dolist (fn cov-fun)
      (when (equal filepath (car fn))
        (addf provs fn)))

    (with-open-file (f filepath :direction :input)
      (loop
       (let ((line (nth-value 0 (read-line f nil nil))))
         (unless line (return 'eof))
         (addf lines line))))

    (setq lines (colorize-lines lines provs))

    (unless destination (setq destination t))
    (format destination "~A~%" filepath)
    (let ((count 1))
      (dolist (line lines)
        (format destination "~A~4,'0D~A| ~A~%" *ansi-gray* count *ansi-reset* line)
        (incf count)))
    (format destination "~A------------------------------------------------------------
Coverage: ~,1F%~%" *ansi-reset* (calculate-coverage cov-fun filepath))))

(defun display-coverage (cover filepaths &optional destination &key include exclude)
  "Display coverage of the listed filepaths."
  (cond ((emptyp filepaths)
         (display-file-list cover includes excludes))
        (t
         (dolist (filepath filepaths)
           (display-cover-file cover filepath destination)))))

(defun run-for-cover ()
  "Parses the command line arguments and runs the coverage display code."
  (let (includes
        include-next
        excludes
        exclude-next
        cover
        files)
    (dolist (arg (subseq *app-args* 2))
      (cond (include-next (addf includes arg) (setq include-next nil))
            (exclude-next (addf excludes arg) (setq exclude-next nil))
            ((or (string= arg "-i") (string= arg "--include")) (setq include-next t))
            ((or (string= arg "-x") (string= arg "--exclude")) (setq exclude-next t))
            ((string= arg "-h") (panic :help))
            (cover (addf files arg))
            (t
             (with-open-file (f arg :direction :input)
               (setq cover (read f))))))
    (unless cover (panic "Missing coverage file."))
    (display-coverage cover files t :include includes :exclude excludes)))

(recover r (display-help r)
         (run-for-cover))
