#!/usr/bin/env slipr

;;;; Copyright (c) 2026, Peter Ohler, All rights reserved.

(defun display-help (&optional err)
  (typecase err
    (error (format t "~%>>> ~A <<<~%" (send err :message)))
    (string (format t "~%>>> ~A <<<~%" err))
    (t nil))
  (format t "~%~A

Explore the coverage of lisp code. The first argument must be a path to a
coverage file generated by slip. If no other filepaths are provided a list of
the filepaths in the coverage file are listed. If additional filepaths are
provided then the file is displayed with colors indicating whether a function
was called. A coverage percentage is display at the end of the file.

usage: ~A <coverage-file> [<filepath>...]
" (cadr *app-args*) (cadr *app-args*))
  (format t "  -i --include <regex>  include file (default: all files) ~%")
  (format t "  -x --exclude <regex>  exclude file (default: no exclusions) ~%")
  (format t "  -h --help             display help~%")
  (terpri))

(defun calculate-coverage (cov-fun filepath)
  "Calculates the coverage percentage for a file if filepath is a string. If
   filepath is nil then the overall coverage is calculated. If filepath is a
   list of files then only files in the list are used for the summary."
  (let ((covered 0)
        (total 0))

    (dolist (fn cov-fun)
      (when (or (null filepath)
                (and (stringp filepath) (suffixp (car fn) filepath))
                (and (listp filepath) (member (car fn) filepath)))
        (incf total)
        (unless (= 0 (nth 5 fn)) (incf covered))))

    (cond ((= total 0) 0)
          (t (/ (* covered 100) total)))))

(defun filter-filepath (filepath includes excludes)
  "File a pathname with the includes and excludes where both the includes and
   excludes are lists of regexp strings. A filepath passes if it is in the
   includes and not in the excludes. An empty or nil includes passes any
   filepath unless it matches a regexp in the excludes."
  (let ((pass (emptyp includes)))
    (dolist (rx includes)
      (when (regex-match rx filepath) (setq pass t)))
    (dolist (rx excludes)
      (when (regex-match rx filepath) (setq pass nil)))
    pass))

(defun display-file-list (cover includes excludes)
  "Display a list of the files in the coverage information along with the
   coverage of each and the overall coverage."
  (let ((cov-files (car cover))
        filepaths)
    (loop
     (when (emptyp cov-files) (return 'done))
     (when (filter-filepath (car cov-files) includes excludes)
       (addf filepaths (car cov-files)))
     (setq cov-files (cddr cov-files)))

    (sort filepaths)

    (dolist (filepath filepaths)
      (format t "~A: ~,1F%~%" filepath (calculate-coverage (cdr cover) filepath)))

    (format t "Total coverage: ~,1F%~%" (calculate-coverage (cdr cover) filepaths))))

(defun insert (seq pos item)
  "A general list insertion function."
  (cond ((= pos 0) (cons item seq))
        ((<= (length seq) pos) (add seq item))
        (t (append (add (subseq seq 0 pos) item) (subseq seq pos)))))

(defun add-prov (segments c0 c1 cov)
  "Add a provenance segment for a function as described by c0, the first column,
and c1, the last column along with the coverage. Segments are a list of
function provenance triplets. Consideration is given to the relationship of
the new segment and it's coverage."
  (dotimes (n (length segments))
    (let ((seg (nth n segments)))
      (cond ((and (= (car seg) c0) (= (cadr seg) c1))
             ;; Function is the same as seg. This happens when replaing an initial segment for a full line.
             (setf (caddr seg) cov))

            ((and (= (car seg) c0) (<= c1 (cadr seg)))
             ;; Function is inside the seg with the same left edge.
             (unless (equal (caddr seg) cov)
               (setf (car seg) c1)
               (setq segments (insert segments n (list c0 c1 cov)))))
            ((and (<= (car seg) c0) (= c1 (cadr seg)))
             ;; Function is inside the seg with the same right edge.
             (unless (equal (caddr seg) cov)
               (setf (cadr seg) c0)
               (setq segments (insert segments (1+ n) (list c0 c1 cov)))))
            ((and (<= (car seg) c0) (<= c1 (cadr seg)))
             ;; Function is inside the seg with the same right edge.
             (unless (equal (caddr seg) cov)
               (setq segments (insert segments (1+ n) (list c1 (cadr seg) (caddr seg))))
               (setq segments (insert segments (1+ n) (list c0 c1 cov)))
               (setf (cadr seg) c0)))

            ((and (= c0 (car seg)) (<= (cadr seg) c1))
             ;; Function wraps the seg with the same left edge.
             (if (equal (caddr seg) cov)
                 (setf (cadr seg) c1)
                 (setq segments (insert segments (1+ n) (list (cadr seg) c1 cov)))))
            ((and (<= c0 (car seg)) (= (cadr seg) c1))
             ;; Function wraps the seg with the same right edge.
             (if (equal (caddr seg) cov)
                 (setf (car seg) c0)
                 (setq segments (insert segments n (list c0 (car seg) cov)))))
            ((and (<= c0 (car seg)) (<= (cadr seg) c1))
             ;; Function wraps the seg.
             (cond ((equal (caddr seg) cov)
                    (setf (car seg) c0)
                    (setf (cadr seg) c1))
                   (t
                    (setq segments (insert segments (1+ n) (list (cadr seg) c1 cov)))
                    (setq segments (insert segments n (list c0 (car seg) cov))))))

            (t nil))))
  segments)

(defun form-segments (provs lines)
  "Form a set of segments where each segment is a list of coverage markers that
can be used to write a colorized version of a text line."
  (let ((seg-sets (mapcar (lambda (line) (list (list 0 (length line) nil))) lines)))

    (dolist (fn provs)
      (let* ((first-line (cadr fn)) ;; lines are zero based
             (cov (if (< 0 (nth 5 fn)) :covered :not-covered))
             (last-line (cadddr fn))
             (c0 (1- (caddr fn))) ;; columns are 1 based
             (c1 (nth 4 fn))) ;; one past last character

        (when (< c0 0) (setq c0 0))
        ;; First determine if the function spans multiple lines.
        (cond ((= first-line last-line) ;; one line
               (setf (nth first-line seg-sets) (add-prov (nth first-line seg-sets) c0 c1 cov)))
              (t ;; multiple lines
               (setf (nth first-line seg-sets) (add-prov (nth first-line seg-sets) c0 (length (nth first-line lines)) cov))
               (dotimes (n (- last-line first-line 1))
                       (let ((mid (+ first-line n 1)))
                         (setf (nth mid seg-sets) (add-prov (nth mid seg-sets) 0 (length (nth mid lines)) cov))))
               (setf (nth last-line seg-sets) (add-prov (nth last-line seg-sets) 0 c1 cov))))))
    seg-sets))

(defun colorize-lines (lines provs)
  (let ((segments (form-segments provs lines)))
    ;; Use the segments to reform each line with colors.
    (dotimes (n (length lines))
      (let ((line (nth n lines))
            (sline (nth n segments))
            (current-color *ansi-gray*)
            (colorized ""))
        (dolist (seg (nth n segments))
          (setq current-color (case (caddr seg)
                                (:covered *ansi-green*)
                                (:not-covered *ansi-red*)
                                (t *ansi-gray*)))
          (setq colorized (string-append colorized current-color))
          (let ((last (cadr seg)))
            (cond ((< (length line) last)
                   (setq colorized (string-append colorized (subseq line (car seg)))))
                  (t
                   (setq colorized (string-append colorized (subseq line (car seg) last)))))))
        (let ((last (cadar (last (nth n segments)))))
          (when (and (<= 0 last) (< last (length line)))
            (setq colorized (string-append colorized
                                           (if (< (1+ last) (length line)) (subseq line last (1+ last)) "")
                                           current-color
                                           (subseq line (1+ last))))))
        (setf (nth n lines) colorized))))
  lines)

(defun display-cover-file (cover filepath destination)
  "Output a file colorized according to the coverage of each function."
  (let ((cov-fun (cdr cover))
        lines
        provs)
    ;; The filepath may be a partial path so find the first match and use that
    ;; as the target filepath.
    (setq filepath
          (dolist (fn cov-fun)
            (when (suffixp (car fn) filepath)
              (return (car fn)))))

    (dolist (fn cov-fun)
      (when (equal filepath (car fn))
        (addf provs fn)))

    (with-open-file (f filepath :direction :input)
      (loop
       (let ((line (nth-value 0 (read-line f nil nil))))
         (unless line (return 'eof))
         (addf lines line))))

    (setq lines (colorize-lines lines provs))

    (unless destination (setq destination t))
    (format destination "~A~%" filepath)
    (let ((count 1))
      (dolist (line lines)
        (format destination "~A~4,'0D~A| ~A~%" *ansi-gray* count *ansi-reset* line)
        (incf count)))
    (format destination "~A------------------------------------------------------------
Coverage: ~,1F%~%" *ansi-reset* (calculate-coverage cov-fun filepath))))

(defun display-coverage (cover filepaths &optional destination &key include exclude)
  "Display coverage of the listed filepaths."
  (cond ((emptyp filepaths)
         (display-file-list cover includes excludes))
        (t
         (dolist (filepath filepaths)
           (display-cover-file cover filepath destination)))))

(defun run-for-cover ()
  "Parses the command line arguments and runs the coverage display code."
  (let (includes
        include-next
        excludes
        exclude-next
        cover
        files)
    (dolist (arg (subseq *app-args* 2))
      (cond (include-next (addf includes arg) (setq include-next nil))
            (exclude-next (addf excludes arg) (setq exclude-next nil))
            ((or (string= arg "-i") (string= arg "--include")) (setq include-next t))
            ((or (string= arg "-x") (string= arg "--exclude")) (setq exclude-next t))
            ((string= arg "-h") (panic :help))
            (cover (addf files arg))
            (t
             (with-open-file (f arg :direction :input)
               (setq cover (read f))))))
    (unless cover (panic "Missing coverage file."))
    (display-coverage cover files t :include includes :exclude excludes)))

(recover r (display-help r)
         (run-for-cover))
