#!/usr/bin/env slipr

;;;; Copyright (c) 2026, Peter Ohler, All rights reserved.

(defun display-help (&optional error-message)
  (when error-message (format t "~%>>> ~A <<<~%" error-message))
  (format t "~%~A

Explore the coverage of lisp code. The first argument must be a path to a
coverage file generated by slip. If no other filepaths are provided a list of
the filepaths in the coverage file are listed. If additional filepaths are
provided then the file is displayed with colors indicating whether a function
was called. A coverage percentage is display at the end of the file.

usage: ~A <coverage-file> [<filepath>...]

" (cadr *app-args*) (cadr *app-args*)))

(defun calculate-coverage (cov-fun filepath)
  "Calculates the coverage percentage for a file of if no filepath is provided
   then overall coverage is calculated."
  (let ((covered 0)
        (total 0))

    (dolist (fn cov-fun)
      (when (or (null filepath) (suffixp (car fn) filepath))
        (setq total (1+ total)
              covered (+ covered (nth 5 fn)))))

    (cond ((= total 0) 0)
          (t (/ (* covered 100) total)))))

(defun display-file-list (cover)
  "Display a list of the files in the coverage information along with the
   coverage of each and the overall coverage."
  (let ((cov-files (car cover))
        filepaths)
    (loop
     (when (emptyp cov-files) (return 'done))
     (addf filepaths (car cov-files))
     (setq cov-files (cddr cov-files)))

    (sort filepaths)

    (dolist (filepath filepaths)
      (format t "~A: ~,1F%~%" filepath (calculate-coverage (cdr cover) filepath)))

    (format t "Total coverage: ~,1F%~%" (calculate-coverage (cdr cover) nil))))

(defun display-cover-file (cover filepath)
  (let ((cov-fun (cdr cover))
        lines)
    ;; The filepath may be a partial path so find the first match and use that
    ;; as the target filepath.
    (setq filepath
          (dolist (fn cov-fun)
            (when (suffixp (car fn) filepath)
              (return (car fn)))))

    (with-open-file (f filepath :direction :input)
      (loop
       (let ((line (nth-value 0 (read-line f nil nil))))
         (unless line (return 'eof))
         (addf lines line))))

    ;; TBD read file into memory as lines of string

    ;; collect coverage func info, should already be sorted

    ;; keep a stack of colors
    ;; walk lines and cov-fun and insert color changes as needed
    ;; print lines with line numbers

    (format t "~A~%" filepath)
    (let ((count 1))
      (dolist (line lines)
        (format t "~4,'0D| ~A~%" count line)
        (incf count)))
    (format t "------------------------------------------------------------
Coverage: ~,1F%~%" (calculate-coverage cov-fun filepath))))

(defun display-coverage (cover filepaths)
  "Display coverage of then listed filepaths."
  (cond ((emptyp filepaths)
         (display-file-list cover))
        (t
         (dolist (filepath filepaths)
           (display-cover-file cover filepath)))))

;;; Handle the command lines arguments and kick off the processing.
(cond ((or (member "-h" *app-args*) (member "-help" *app-args*))
       (display-help))
      ((< (length *app-args*) 3)
       (display-help "missing coverage-file"))
      (t
       (recover r (progn
                    (when (typep r 'error) (setq r (send r :message)))
                    (display-help r))
                (let ((cover (with-open-file (f (caddr *app-args*) :direction :input)
                               (read f))))
                  (display-coverage cover (cdddr *app-args*))))))
